import { useEffect, useState } from 'react';
import Head from 'next/head'
import { volume, fullscreen, blobImg } from "../assets/icons/index"
// icons
import { BiSkipPrevious, BiSkipNext, BiPlay, BiPause } from 'react-icons/bi';
// styles
import styles from "../styles/Home.module.scss"

import screenfull from 'screenfull';

// import { songLists } from "../components/songLists/songLists"





export default function Home() {

  const [play, setPlay] = useState(false)
  const [songList, setSongsLists] = useState(1)

  const play_pause_btn = () => {
    if (play) {
      setPlay(false)
    } else if (!play) {
      setPlay(true)
    }
  }


  // useEffect(() => {
  //   const fullScreen = document.getElementById('fullscreen');
  //   fullScreen.addEventListener("click", ()=>{
  //     if (screenfull.isEnabled) {
  //       screenfull.toggle();
  //     }
  
  //   })
  // }, [])
  return (
    <div className={styles.home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.app__container}>
        <div className={styles.blobImg}>{blobImg}</div>
        <div className={styles.app_data}>
          <span className={styles.circle}></span>
          <div className={styles.slogan}>
            <div className={styles.title}>SWOT Analysis</div>
          </div>
          <div className={styles.blobImg}>{blobImg}</div>
          <div className={styles.description}>A brainstrom session where we identify our strengths, weaknesses, opportunities,
            and threats.
          </div>

          <div className={styles.player}>
            <div className={styles.volume}>
              {volume}
            </div>
            <div className={styles.song_controler}>
              <div className={styles.prev}><BiSkipPrevious /></div>
              <div className={styles.song_lists}><span>01 / 12</span> <span onClick={play_pause_btn} className={styles.btns}>{!play ? <BiPlay /> : <BiPause />}</span></div>
              <div className={styles.next}><BiSkipNext /></div>
            </div>
            <div className={styles.fullscreen} id="fullscreen">{fullscreen}</div>
          </div>
        </div>
      </div>
    </div>
  )
}
